### PR TITLE
Include Raw Net::HTTP response in Error

### PR DESCRIPTION
**Pull request by veverkap**
This code that we had as a monkey patch on Slack::Notifier allows the raw NET::HTTP response to be sent back with the Slack::Notifier::APIError. We thought this would be beneficial to others and allow us to remove the monkey patch from our codebase.

### CODE REVIEW

**Comment by pcraston** [comment]
super useful for me too. any chance this can be merged?

**Comment by siegy22** [comment]
@stevenosloan ping 😉

**Comment by speckins** [comment]
I just came here to create a PR to do exactly this. 😄It would be very useful to have the HTTP response, so we can use the JSON error response object (e.g., `{"retry_after":1,"ok":false,"error":"rate_limited"}`) without having to parse it out of the error message (yuck).

**Comment by siegy22** [comment]
@speckins I hope you apply this patch instead of parsing the JSON out of the error message 😂

**Comment by paprikati** [comment]
This is really useful would be great to merge

**Comment by jamiecobbett** [comment]
@stevenosloan any chance you'll push a release with this to rubygems.org?

**Pull request merged**
